version: 2
updates:
  - package-ecosystem: "npm"
    directories:
      - "/"
      - "/benchmark"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0
    groups:
      security-updates:
        applies-to: security-updates
        patterns:
          - "*"
